### ISSUE TITLE
Icon size in panel is too small

### ISSUE THREAD

**Issue by prateekmedia** [doncsugar/willow-theme#1]
Hi, I found out this theme to be good but still it doesn't have large icon size for icon only task bar even with your recommended settings of 48px panel height, So can there be an option to keep it high by default or to change it manually.

Also Willow theme appears to be available in separate packages and not as a Global theme, so can you upload global theme in pling.

**Comment by doncsugar** [comment]
Hello,

I have been thinking about the icon sizes. Here is the problem: Windows uses 24px icons and KDE uses 22px. I do not think @yeyushengfan258's icon pack has 24px icons. The 32px large icon size is obviously a lot larger than what Windows uses, so I am not sure what to choose. 56px panel height is also an option.

It is possible to change the icon size by adjusting the orange margins in `tasks.svg`. Resize the height of `normal-hint-top-margin` and `normal-hint-bottom-margin` from 12px to 8px and it will display 32px icons. They might look a bit strange, however.

I cannot make a global theme yet because I do not have a way to make an icon pack, I am not finished with the lockscreen, and I have not decided on a desktop configuration.

**Comment by prateekmedia** [comment]
@doncsugar Can you please add large icon by default or as an option cause as I said it is too small and I don't know how to make it large as I don't have experience with it and inkscape.

**Comment by doncsugar** [comment]
I have added an alternative file to have large icons [here](https://github.com/doncsugar/willow-theme/commit/08d565d8a18f279b60400491f70e7f75a98b87f7).

**Comment by prateekmedia** [comment]
Thanks!

**Comment by arun54321** [comment]
I'm using qogir icon theme. but icons in panel are small. 
![image](https://user-images.githubusercontent.com/42943340/132300272-349229ed-3a65-4c84-9473-de37eb3ddb81.png)

**Comment by doncsugar** [comment]
@arun54321 Please resize the panel to 48px or 56px.

**Comment by mcdearman** [comment]
I resized my panel to 56px but it's still got small icons.
![Screenshot_2021-11-06_23-20-42](https://user-images.githubusercontent.com/26758180/140632208-e6f64159-12bd-4f73-bf03-c2f0be00906c.png)

**Comment by prateekmedia** [comment]
@mathlet @doncsugar You just have to replace https://github.com/doncsugar/willow-theme/blob/main/plasma-style/WillowDark/widgets/tasks.svgz with https://github.com/doncsugar/willow-theme/blob/main/plasma-style/WillowDark/widgets/tasksALT.svgz

This was for dark theme, you can repeat the same for light theme with Willow-light folder instead of Willow-dark.

**Comment by mcdearman** [comment]
> @mathlet @doncsugar You just have to replace https://github.com/doncsugar/willow-theme/blob/main/plasma-style/WillowDark/widgets/tasks.svgz with https://github.com/doncsugar/willow-theme/blob/main/plasma-style/WillowDark/widgets/tasksALT.svgz
> 
> This was for dark theme, you can repeat the same for light theme with Willow-light folder instead of Willow-dark.

I did replace it. I'm using the dark theme. I deleted the tasks.svgz and renamed the taskALT. It didn't change the icons.

**Comment by doncsugar** [comment]
@mathlet I think the Win11OS theme has margins for larger icons. As your screenshot shows, the icons will extend outside of the box of the task highlight like your start button icon. It will look something like this:
![image](https://user-images.githubusercontent.com/46570709/140671834-d3ad8042-ca2e-48f3-8daa-afa50ce95a9c.png)
tasksALT is for larger icons at 48px. You are correct that it does not change at 56px.

Sorry, the style doesn't really allow full-height icons.

**Comment by doncsugar** [comment]
The default icon size is now 32px, which should be the same as stock Breeze. The smaller scale, which tends to work better for smaller resolutions, has been moved to its own theme. A global theme is now responsible for setting up the desktop (and panel height) properly.
