### ISSUE TITLE
If you move the panel to the top

### ISSUE THREAD

**Issue by sharp-NEKO** [doncsugar/willow-theme#2]
Hello.
I'm using this theme to create a Linux distribution, but when I apply this Plasma style and move the panel to the top, I get a bug.

**Comment by doncsugar** [comment]
Hi,

Only the bottom panel placement is supported, but top should also work. What is the bug?

**Comment by sharp-NEKO** [comment]
Hi,
I didn't know about that, sorry.

But the bug is like this.
↓Please watch.
（I dared to keep it private.）

When I move the panel to the top, the indicator doesn't show up at all and I can't tell if the software is open or not.
This is happening in KDE 22.4.

**Comment by doncsugar** [comment]
Looking at your video, I noticed that the icons are also off-center. As you can see in my screenshot, the top and bottom have equal space.
![image](https://user-images.githubusercontent.com/46570709/132590881-22f0f15c-83ca-4405-a1de-d0bc3e30df7d.png)
My Plasma version is 5.22.5, but I believe this worked on 5.22.4 as well. I am using KDE neon with the "Icons-only Task Manager." Which distro are you using? Something is definitely different.

**Comment by sharp-NEKO** [comment]
Sorry, I forgot to mention.

I felt that the icon was too small for the icon, so I looked at another issue and adjusted the icon size.
However, the same bug occurred when the icon size was standard!

**Comment by sharp-NEKO** [comment]
And I'm using KDE neon.

**Comment by doncsugar** [comment]
I will check if I can reproduce this on a live USB of KDE neon user edition.

I noticed that your panel height was 44px. I understand that you have a smaller display size, but you will get the same icon size with the default theme at 48px panel height. Did you try that before editing the files?

**Comment by doncsugar** [comment]
I was able to reproduce it. It seems that the task manager works differently now. I have added support for top panel placement again [here](https://github.com/doncsugar/willow-theme/commit/7b8da5147ba2bfa4e230173ec0b1b7c78001286d).

Thank you for reporting this.

**Comment by sharp-NEKO** [comment]
Thank you very much! I'm cured.

However, the same thing has happened with the black theme.

**Comment by doncsugar** [comment]
I had not fixed dark's yet. You can try it now.

**Comment by sharp-NEKO** [comment]
![Screenshot_20210911_233224](https://user-images.githubusercontent.com/65962822/132951321-c7393808-d53e-44fc-a6d0-8d8dc037f4a2.png)
![Screenshot_20210911_233203](https://user-images.githubusercontent.com/65962822/132951331-a6327b79-d4a8-4446-b102-15b51f396c27.png)

Thank you very much!!
