### ISSUE TITLE
Icons are too Small

### ISSUE THREAD

**Issue by HaroonRehman** [doncsugar/willow-theme#4]
ICons are too Small plzz fix it  

See the Terminal Icon 

![image](https://user-images.githubusercontent.com/76829403/167606419-251ceae7-4fa6-4ec5-b128-9eb4a6b8eec7.png)

![image](https://user-images.githubusercontent.com/76829403/167606567-7225c74e-acce-4092-8d5a-962775b26e06.png)

**Comment by doncsugar** [comment]
Hello,

Unfortunately, Willow Dark is still in beta and will not receive updates.

For now, you can use [Willow Desktop](https://store.kde.org/p/1735447) with a dark color scheme.

You can use [Willow Spectrum](https://store.kde.org/p/1735447) for larger icons.

You should ask the maker of your icon theme to fix the terminal icon.

**Comment by HaroonRehman** [comment]
> icon

dear, In Willow spectrum I have to use dark theme which I do not want to use. And there is no Willow Desktop. So Please Make this Willow dark's icon large and launch another Plasma style with small icons like Willow dark small icons just like you did with Willow light small Icons

**Comment by doncsugar** [comment]
Sorry, but I am still working on getting Willow out of beta.

You can set [Willow Spectrum](https://www.pling.com/p/1757048) to Dark by:

1. Installing [Willow Spectrum](https://www.pling.com/p/1757048) and [Willow Dark](https://www.pling.com/p/1562235)

2. Copy the dark color scheme to Spectrum and name it `colors` with this command:
`cp ~/.local/share/color-schemes/WillowDark.colors ~/.local/share/plasma/desktoptheme/willow-spectrum-plasma/colors`

Reapply the Plasma Theme and your panel should be dark. You should still ask the maker of your icon theme to fix the terminal icon.

**Comment by doncsugar** [comment]
Willow Dark now features large icons by default and the Small Icons variant is a separate download.

The mixed up icon theme is likely a KDE bug, but the other icons are not Willow's and can only be fixed by their developer. Willow's full-color icons are from Papirus.
