### ISSUE TITLE
weird black bars at the bottom of windows using willow dark blur window decoration 

### ISSUE THREAD

**Issue by ZacBozer** [doncsugar/willow-theme#9]
![Screenshot_20240703_012251](https://github.com/doncsugar/willow-theme/assets/63252006/efc01c46-cd1e-4253-8298-660e32d8d9c2)

**Comment by doncsugar** [comment]
Hi @ZacBozer,
This is completely normal and is just how the theme looks and is a limitation of the Aurorae engine. The store page recommends using the decoration with "No Side Window Borders". However, in your case it looks like you should use the shader theme with "No Window Borders". Here is an example shader: https://github.com/a-parhom/LightlyShaders/tree/plasma6

**Comment by ZacBozer** [comment]
I can't seem to be able to install it on arch

> Hi @ZacBozer, This is completely normal and is just how the theme looks and is a limitation of the Aurorae engine. The store page recommends using the decoration with "No Side Window Borders". However, in your case it looks like you should use the shader theme with "No Window Borders". Here is an example shader: https://github.com/a-parhom/LightlyShaders/tree/plasma6
